# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Weekly lessons
contact_us: Un article à proposer? Une question à poser? Ou juste envie de parler? Écrivez-nous!
email: contact@doctoubib.com
description: > # this means to ignore newlines until "baseurl:"
  Un site pour regrouper toutes les bonnes pratiques de l'IT Doctoubib
continue_reading : Lire la suite...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doctoubib.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  doctoubib
disqusid: "doctoubib"
collections:
- members

# Build settings
markdown: kramdown

# theme: jekyll-theme-midnight
